"use client";

import { FormEvent, useMemo, useState } from "react";
import { cancelMeetup, completeMeetup, createPlanItem, deletePlanItem, reorderPlanItems, searchPlaces, setPlanItemStatus, updatePlanItem, type PlanItemInput } from "@/services/meetup-repository";
import type { Location, MeetupDetail, PlanItem, PlanItemStatus, PlanItemType } from "@/types/meetup";
import { useLanguage } from "./language-provider";

const types: Array<{ value: PlanItemType; ko: string; ja: string; icon: string }> = [
  { value: "meet", ko: "집합", ja: "集合", icon: "📍" }, { value: "food", ko: "식사", ja: "食事", icon: "🍽" }, { value: "activity", ko: "활동", ja: "遊び", icon: "✨" }, { value: "cafe", ko: "카페", ja: "カフェ", icon: "☕" }, { value: "move", ko: "이동", ja: "移動", icon: "🚶" }, { value: "other", ko: "기타", ja: "その他", icon: "•" }, { value: "end", ko: "해산", ja: "解散", icon: "👋" },
];

function timeInput(value?: string) {
  if (!value) return "";
  const date = new Date(value);
  const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Tokyo", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(date);
  const part = (kind: Intl.DateTimeFormatPartTypes) => parts.find((item) => item.type === kind)?.value ?? "";
  return `${part("hour")}:${part("minute")}`;
}

function dateAtTime(baseValue: string | undefined, time: string) {
  const base = baseValue ? new Date(baseValue) : new Date();
  const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Tokyo", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(base);
  const part = (kind: Intl.DateTimeFormatPartTypes) => parts.find((item) => item.type === kind)?.value ?? "";
  return new Date(`${part("year")}-${part("month")}-${part("day")}T${time}:00+09:00`).toISOString();
}

export function EventPlanPanel({ meetupId, detail, isHost }: { meetupId: string; detail: MeetupDetail; isHost: boolean }) {
  const { language, locale } = useLanguage();
  const korean = language === "ko";
  const canEdit = isHost || detail.meetup.allowPlanEditing === true;
  const [editing, setEditing] = useState<PlanItem>();
  const [title, setTitle] = useState(""); const [type, setType] = useState<PlanItemType>("other"); const [scheduledAt, setScheduledAt] = useState(""); const [note, setNote] = useState("");
  const [placeQuery, setPlaceQuery] = useState(""); const [place, setPlace] = useState<Location>(); const [placeResults, setPlaceResults] = useState<Location[]>([]);
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string>(); const [dragId, setDragId] = useState<string>();
  const dateTime = (value?: string) => value ? new Intl.DateTimeFormat(locale, { timeZone: "Asia/Tokyo", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(value)) : korean ? "시간 미정" : "時間未定";
  const reset = () => { setEditing(undefined); setTitle(""); setType("other"); setScheduledAt(""); setNote(""); setPlaceQuery(""); setPlace(undefined); setPlaceResults([]); };
  const startEdit = (item: PlanItem) => { setEditing(item); setTitle(item.title); setType(item.type); setScheduledAt(timeInput(item.scheduledAt)); setNote(item.note ?? ""); setPlace(item.place); setPlaceQuery(item.place?.name ?? ""); setPlaceResults([]); };
  const input = (): PlanItemInput => ({ type, title: title.trim(), ...(place ? { place } : {}), ...(scheduledAt ? { scheduledAt: dateAtTime(detail.meetup.confirmedDateTime ?? detail.candidateSlots[0]?.startDateTime, scheduledAt) } : {}), ...(note.trim() ? { note: note.trim() } : {}), source: editing?.source ?? "manual" });
  const save = async (event: FormEvent) => { event.preventDefault(); if (!title.trim()) return; setBusy(true); setError(undefined); try { if (editing) await updatePlanItem(meetupId, editing.id, input()); else await createPlanItem(meetupId, input()); reset(); } catch (caught) { setError(caught instanceof Error ? caught.message : korean ? "당일 일정을 저장하지 못했어요." : "当日の予定を保存できませんでした。"); } finally { setBusy(false); } };
  const findPlace = async () => { if (!placeQuery.trim()) return; setBusy(true); try { setPlaceResults(await searchPlaces(placeQuery)); } catch { setError(korean ? "장소를 검색하지 못했어요." : "場所を検索できませんでした。"); } finally { setBusy(false); } };
  const remove = async (item: PlanItem) => { if (!window.confirm(korean ? `‘${item.title}’ 항목을 삭제할까요?` : `「${item.title}」を削除しますか？`)) return; setBusy(true); try { await deletePlanItem(meetupId, item.id); if (editing?.id === item.id) reset(); } catch (caught) { setError(caught instanceof Error ? caught.message : korean ? "항목을 삭제하지 못했어요." : "項目を削除できませんでした。"); } finally { setBusy(false); } };
  const changeStatus = async (item: PlanItem, status: PlanItemStatus) => { setBusy(true); try { await setPlanItemStatus(meetupId, item.id, status); } catch (caught) { setError(caught instanceof Error ? caught.message : korean ? "상태를 바꾸지 못했어요." : "状態を変更できませんでした。"); } finally { setBusy(false); } };
  const reorder = async (fromId: string, toId: string) => { if (fromId === toId || !canEdit) return; const ids = detail.planItems.map((item) => item.id); const from = ids.indexOf(fromId); const to = ids.indexOf(toId); ids.splice(to, 0, ids.splice(from, 1)[0]); setBusy(true); try { await reorderPlanItems(meetupId, ids); } catch (caught) { setError(caught instanceof Error ? caught.message : korean ? "순서를 바꾸지 못했어요." : "順番を変更できませんでした。"); } finally { setBusy(false); setDragId(undefined); } };
  const move = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= detail.planItems.length) return; void reorder(detail.planItems[index].id, detail.planItems[target].id); };
  const topVotes = useMemo(() => detail.contentOptions.map((option) => ({ option, count: detail.contentVotes.filter((vote) => vote.optionId === option.id).length })).filter((item) => item.count > 0).sort((a, b) => b.count - a.count).slice(0, 3), [detail.contentOptions, detail.contentVotes]);
  if (detail.meetup.status === "CANCELLED") return null;
  return <section className="event-plan-panel"><div className="plan-heading"><div><p className="eyebrow">{korean ? "당일 플랜" : "当日の予定"}</p><h2>{korean ? "그날의 계획" : "当日のプラン"}</h2><p>{korean ? "계획과 실제 진행을 함께 기록해요." : "予定と実際の進行を一緒に記録します。"}</p></div>{isHost && detail.meetup.status !== "COMPLETED" && <div className="event-status-actions"><button type="button" className="text-button" onClick={() => void cancelMeetup(meetupId)} disabled={busy}>{korean ? "약속 취소" : "予定を中止"}</button><button type="button" className="secondary-button" onClick={() => void completeMeetup(meetupId)} disabled={busy}>{korean ? "약속 완료" : "予定を完了"}</button></div>}</div>
    {detail.meetup.status === "COMPLETED" && <p className="completed-note">✓ {korean ? "완료된 약속은 자동으로 그룹과 친구 히스토리에 남아요." : "完了した予定はグループと友だちの履歴に自動で残ります。"}</p>}
    {topVotes.length > 0 && <div className="plan-vote-hints">{korean ? "투표 결과" : "投票結果"}: {topVotes.map(({ option, count }) => <button type="button" key={option.id} onClick={() => { setTitle(option.label); setType(option.category === "FOOD" ? "food" : "activity"); }} disabled={!canEdit}>{option.label} <b>{count}</b></button>)}</div>}
    {detail.planItems.length === 0 ? <p className="empty-note">{korean ? "아직 등록된 당일 일정이 없어요." : "当日の予定はまだありません。"}</p> : <ol className="plan-list">{detail.planItems.map((item, index) => { const meta = types.find((candidate) => candidate.value === item.type)!; return <li key={item.id} draggable={canEdit} onDragStart={() => setDragId(item.id)} onDragOver={(event) => event.preventDefault()} onDrop={() => { if (dragId) void reorder(dragId, item.id); }} className={`plan-item ${item.status}`}><div className="plan-marker">{item.status === "completed" ? "✓" : item.status === "skipped" ? "–" : meta.icon}</div><div className="plan-main"><small>{dateTime(item.scheduledAt)}</small><b>{item.title}</b>{item.place && <a href={`https://www.google.com/maps/search/?api=1&query_place_id=${encodeURIComponent(item.place.placeId.replace(/^places\//, ""))}&query=${encodeURIComponent(item.place.name)}`} target="_blank" rel="noreferrer">📍 {item.place.name}</a>}{item.note && <p>{item.note}</p>}</div><div className="plan-actions"><select value={item.status} aria-label={korean ? "일정 상태" : "予定の状態"} onChange={(event) => void changeStatus(item, event.target.value as PlanItemStatus)} disabled={busy || detail.meetup.status === "COMPLETED"}><option value="planned">{korean ? "예정" : "予定"}</option><option value="completed">{korean ? "완료" : "完了"}</option><option value="skipped">{korean ? "건너뜀" : "スキップ"}</option></select>{canEdit && detail.meetup.status !== "COMPLETED" && <><span className="plan-move-controls"><button type="button" className="text-button" aria-label={korean ? "위로 이동" : "上へ移動"} disabled={busy || index === 0} onClick={() => move(index, -1)}>↑</button><button type="button" className="text-button" aria-label={korean ? "아래로 이동" : "下へ移動"} disabled={busy || index === detail.planItems.length - 1} onClick={() => move(index, 1)}>↓</button></span><button type="button" className="text-button" onClick={() => startEdit(item)}>{korean ? "수정" : "編集"}</button><button type="button" className="text-button danger-button" onClick={() => void remove(item)}>{korean ? "삭제" : "削除"}</button></>}</div></li>; })}</ol>}
    {canEdit && detail.meetup.status !== "COMPLETED" && <form className="plan-form" onSubmit={(event) => void save(event)}><h3>{editing ? (korean ? "일정 수정" : "予定を編集") : (korean ? "+ 일정 추가" : "+ 予定を追加")}</h3><div className="plan-form-grid"><label><span>{korean ? "종류" : "種類"}</span><select value={type} onChange={(event) => setType(event.target.value as PlanItemType)}>{types.map((item) => <option value={item.value} key={item.value}>{item.icon} {korean ? item.ko : item.ja}</option>)}</select></label><label><span>{korean ? "시간만 선택" : "時刻だけ選択"}</span><input type="time" value={scheduledAt} onChange={(event) => setScheduledAt(event.target.value)} /></label></div><label><span>{korean ? "제목" : "タイトル"}</span><input value={title} maxLength={120} onChange={(event) => setTitle(event.target.value)} placeholder={korean ? "예: 横浜駅에서 만나기" : "例：横浜駅で集合"} required /></label><label><span>{korean ? "장소 · 선택" : "場所・任意"}</span><div className="plan-place-search"><input value={placeQuery} onChange={(event) => { setPlaceQuery(event.target.value); if (!event.target.value) setPlace(undefined); }} placeholder={korean ? "장소 검색" : "場所を検索"} /><button type="button" className="text-button" onClick={() => void findPlace()} disabled={busy}>{korean ? "검색" : "検索"}</button></div></label>{placeResults.length > 0 && <div className="plan-place-results">{placeResults.map((item) => <button key={item.placeId} type="button" onClick={() => { setPlace(item); setPlaceQuery(item.name); setPlaceResults([]); }}><b>{item.name}</b><small>{item.address}</small></button>)}</div>}<label><span>{korean ? "메모 · 선택" : "メモ・任意"}</span><textarea rows={2} value={note} maxLength={500} onChange={(event) => setNote(event.target.value)} /></label><div className="plan-form-actions"><button type="submit" className="secondary-button" disabled={busy}>{busy ? korean ? "저장 중..." : "保存中…" : editing ? korean ? "변경 저장" : "変更を保存" : korean ? "일정 추가" : "予定を追加"}</button>{editing && <button type="button" className="text-button" onClick={reset}>{korean ? "취소" : "キャンセル"}</button>}</div></form>}
    {error && <p className="error-message">{error}</p>}
  </section>;
}
