"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { onAuthStateChanged } from "firebase/auth";
import { continueWithGoogle, ensureAnonymousUser, firebase } from "@/lib/firebase/client";
import { createRoom, getMyRooms, joinRoom, saveDefaultOrigin, saveProfile, searchPlaces } from "@/services/meetup-repository";
import type { Location, Room } from "@/types/meetup";
import { useLanguage } from "./language-provider";
import { RelationshipList } from "./relationship-list";

export function ProfileDashboard() {
  const { language } = useLanguage(); const korean = language === "ko"; const router = useRouter();
  const [name, setName] = useState(""); const [anonymous, setAnonymous] = useState(true); const [rooms, setRooms] = useState<Room[]>([]); const [roomName, setRoomName] = useState(""); const [inviteCode, setInviteCode] = useState(""); const [originQuery, setOriginQuery] = useState(""); const [originResults, setOriginResults] = useState<Location[]>([]); const [defaultOrigin, setDefaultOrigin] = useState<Location>(); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  const loadRooms = async () => { try { setRooms(await getMyRooms()); } catch { setRooms([]); } };
  useEffect(() => { const start = async () => { const user = await ensureAnonymousUser(); setName(user.displayName ?? ""); }; void start(); const stop = onAuthStateChanged(firebase().auth, (user) => { setName(user?.displayName ?? ""); setAnonymous(user?.isAnonymous ?? true); if (user && !user.isAnonymous) void loadRooms(); }); return () => stop(); }, []);
  const upgrade = async () => { setBusy(true); setError(undefined); try { const user = await continueWithGoogle(); const profile = await saveProfile(user.displayName || name || "aimasho user"); setName(profile.displayName); await loadRooms(); } catch (caught) { setError(caught instanceof Error ? caught.message : korean ? "Google 계정 연결을 완료하지 못했어요." : "Googleアカウントを連携できませんでした。"); } finally { setBusy(false); } };
  const addRoom = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(undefined); try { await createRoom(roomName, name || "aimasho user"); setRoomName(""); await loadRooms(); } catch (caught) { setError(caught instanceof Error ? caught.message : korean ? "그룹을 만들지 못했어요." : "グループを作成できませんでした。"); } finally { setBusy(false); } };
  const enterRoom = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(undefined); try { const id = await joinRoom(inviteCode, name || "aimasho user"); router.push(`/rooms/${id}`); } catch (caught) { setError(caught instanceof Error ? caught.message : korean ? "그룹에 참여하지 못했어요." : "グループに参加できませんでした。"); } finally { setBusy(false); } };
  const findOrigin = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { setOriginResults(await searchPlaces(originQuery)); } catch (caught) { setError(caught instanceof Error ? caught.message : korean ? "장소를 찾지 못했어요." : "場所を見つけられませんでした。"); } finally { setBusy(false); } };
  const setOrigin = async (origin: Location) => { setBusy(true); try { await saveDefaultOrigin(origin); setDefaultOrigin(origin); setOriginResults([]); } catch (caught) { setError(caught instanceof Error ? caught.message : korean ? "기본 출발 위치를 저장하지 못했어요." : "既定の出発地を保存できませんでした。"); } finally { setBusy(false); } };
  return <main className="profile-page"><p className="eyebrow">{korean ? "나의 AIMASHO" : "わたしの AIMASHO"}</p><h1>{name || (korean ? "내" : "わたしの")}{korean ? "의 약속" : "予定"}</h1>{anonymous ? <section className="account-card group-account-prompt"><div><p className="eyebrow">{korean ? "그룹 시작하기" : "グループを始める"}</p><h2>{korean ? "그룹을 만들거나 참여하려면 로그인해 주세요" : "グループの作成・参加にはログインが必要です"}</h2><p>{korean ? "Google 계정 하나로 그룹 멤버, 다음 일정, 함께한 기록을 여러 기기에서 이어볼 수 있어요." : "Googleアカウントで、メンバー・次の予定・一緒に過ごした記録を複数の端末から確認できます。"}</p><div className="group-login-benefits"><span>✓ {korean ? "그룹 만들기와 초대" : "グループ作成と招待"}</span><span>✓ {korean ? "초대 코드로 참여" : "招待コードで参加"}</span></div></div><button className="primary-button" onClick={() => void upgrade()} disabled={busy}>{busy ? korean ? "로그인 중..." : "ログイン中…" : korean ? "Google로 로그인 / 회원가입" : "Googleでログイン・新規登録"}</button></section> : <><RelationshipList /><section className="room-section"><p className="eyebrow">{korean ? "기본 출발지" : "既定の出発地"}</p><h2>{korean ? "기본 출발 위치" : "既定の出発地"}</h2>{defaultOrigin ? <p className="saved-location">✓ {defaultOrigin.name}</p> : <p className="empty-note">{korean ? "자주 출발하는 장소를 저장해두세요." : "よく出発する場所を保存しましょう。"}</p>}<form className="inline-form" onSubmit={findOrigin}><input value={originQuery} onChange={(event) => setOriginQuery(event.target.value)} placeholder={korean ? "역 / 장소 검색" : "駅・場所を検索"} required /><button className="secondary-button" disabled={busy}>{korean ? "검색" : "検索"}</button></form>{originResults.map((origin) => <button className="profile-place" onClick={() => void setOrigin(origin)} key={origin.placeId}><b>{origin.name}</b><small>{origin.address}</small></button>)}</section><section className="room-section"><div className="section-heading"><div><p className="eyebrow">{korean ? "내 그룹" : "マイグループ"}</p><h2>{korean ? "내 모임" : "マイグループ"}</h2></div></div>{rooms.length === 0 ? <p className="empty-note">{korean ? "아직 그룹이 없어요. 첫 모임을 만들어보세요." : "まだグループはありません。最初のグループを作りましょう。"}</p> : <div className="room-grid">{rooms.map((room) => <Link href={`/rooms/${room.id}`} key={room.id}><span>👥</span><strong>{room.name}</strong><small>{room.role === "OWNER" ? korean ? "관리자" : "管理者" : korean ? "멤버" : "メンバー"}</small></Link>)}</div>}<form className="inline-form" onSubmit={addRoom}><input value={roomName} onChange={(event) => setRoomName(event.target.value)} placeholder={korean ? "새 그룹 이름" : "新しいグループ名"} required /><button className="secondary-button" disabled={busy}>{korean ? "+ 새 그룹" : "+ グループを作る"}</button></form><form className="inline-form" onSubmit={enterRoom}><input value={inviteCode} onChange={(event) => setInviteCode(event.target.value)} placeholder={korean ? "초대 코드" : "招待コード"} required /><button className="secondary-button" disabled={busy}>{korean ? "참여하기" : "参加する"}</button></form></section></>}{error && <p className="error-message">{error}</p>}</main>;
}
